global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "chain-intel"
    static_configs:
      - targets: ["replay:3000"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb:27017"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "hardhat"
    static_configs:
      - targets: ["hardhat:8545"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "alert.rules"
