name: Backend CI/CD Minimal

on:
  push:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.3
          cache: "yarn"
          cache-dependency-path: backend/yarn.lock

      - name: 显示环境信息
        run: |
          node -v
          yarn -v
          ls -la
          pwd
          echo "GitHub Actions环境信息："
          env | grep -E "GITHUB|NODE|PATH|RUNNER"

      - name: 清理并安装依赖
        run: |
          rm -rf node_modules
          yarn cache clean
          yarn install --frozen-lockfile

      - name: 确保Babel插件安装正确
        run: |
          # 确保@babel/plugin-transform-modules-commonjs安装在dependencies中
          yarn add @babel/plugin-transform-modules-commonjs@7.24.0 --exact

          # 检查安装情况
          echo "检查babel插件安装路径和版本:"
          ls -la node_modules/@babel/plugin-transform-modules-commonjs
          yarn why @babel/plugin-transform-modules-commonjs
          node -e "console.log('Babel插件已安装:', require.resolve('@babel/plugin-transform-modules-commonjs'))"

      - name: 创建简单测试文件
        run: |
          mkdir -p src/tests/unit
          echo 'describe("基本测试", () => { test("1+1=2", () => { expect(1+1).toBe(2); }); });' > src/tests/unit/basic.test.js

      - name: 运行简单测试
        run: |
          NODE_OPTIONS="--max-old-space-size=4096" yarn jest src/tests/unit/basic.test.js --no-cache --config=jest.config.js
        env:
          NODE_ENV: test
          BABEL_ENV: test

      - name: 显示项目结构和依赖
        run: |
          echo "项目结构："
          find . -type f -name "*.json" | xargs ls -la

          echo "package.json内容："
          cat package.json

          echo "依赖相关文件："
          find node_modules/@babel -name "plugin-transform-modules-commonjs" -type d | xargs ls -la
