name: Backend CI/CD Minimal

on:
  push:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.3
          cache: "yarn"
          cache-dependency-path: backend/package.json

      - name: 显示环境信息
        run: |
          node -v
          yarn -v
          ls -la
          pwd

      - name: 安装依赖
        run: |
          yarn install --immutable
          yarn list --depth=0

      - name: 检查文件存在
        run: |
          echo "检查关键文件是否存在..."
          ls -la src/tests/unit/
          ls -la minimal-jest.config.js || echo "minimal-jest.config.js 不存在"

      - name: 创建简单测试文件
        run: |
          mkdir -p src/tests/unit
          echo 'describe("简单测试", () => { test("1+1=2", () => { expect(1+1).toBe(2); }); });' > src/tests/unit/simple.test.js
          cat src/tests/unit/simple.test.js

      - name: 创建简单Jest配置
        run: |
          echo 'module.exports = { testEnvironment: "node" };' > simple-jest.config.js
          cat simple-jest.config.js

      - name: 运行极简测试
        run: NODE_ENV=test yarn jest --testMatch="**/src/tests/unit/simple.test.js" --config=simple-jest.config.js
