name: Backend CI/CD Minimal

on:
  push:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.3
          cache: "yarn"
          cache-dependency-path: backend/package.json

      - name: 显示环境信息
        run: |
          node -v
          yarn -v
          ls -la
          pwd
          echo "GitHub Actions环境信息："
          env | grep -E "GITHUB|NODE|PATH|RUNNER"

      - name: 安装依赖
        run: |
          echo "跳过yarn安装，使用纯Node.js"

      - name: 直接运行Node.js脚本
        run: |
          echo 'console.log("测试成功 - 纯Node.js运行正常");' > test.js
          node test.js

      - name: 使用Node.js运行简单测试
        run: |
          echo 'const assert = require("assert"); assert.strictEqual(1+1, 2); console.log("断言测试通过");' > assert-test.js
          node assert-test.js

      - name: 检查package.json
        run: |
          echo "package.json内容："
          cat package.json

      - name: 尝试最小化Jest
        run: |
          echo "安装最小化Jest..."
          npm init -y
          npm install --save-dev jest
          echo 'module.exports = { testEnvironment: "node" };' > jest.config.js
          echo 'describe("最小化测试", () => { test("1+1=2", () => { expect(1+1).toBe(2); }); });' > simple.test.js
          echo "运行最小化Jest..."
          npx jest simple.test.js --no-cache
