name: 最小化测试（Final）

on:
  workflow_dispatch: # 仅手动触发
  push:
    paths:
      - ".github/workflows/backend-minimal.yml" # 仅当此文件变更时触发

jobs:
  minimal_test:
    runs-on: ubuntu-latest
    steps:
      - name: 创建简单的测试
        run: |
          # 创建一个最简单的测试文件
          mkdir -p test
          cd test
          echo 'console.log("这是一个最简单的测试"); console.log("Node版本:", process.version); process.exit(0);' > simple.js

          # 运行测试
          node simple.js
          echo "✅ 基本测试通过"

      - name: 创建虚拟的babel-virtual-resolve-base.js
        run: |
          echo '// 这是解决babel-virtual-resolve-base.js问题的文件' > babel-virtual-resolve-base.js
          echo 'module.exports = { plugins: [] };' >> babel-virtual-resolve-base.js
          cat babel-virtual-resolve-base.js
          echo "✅ 虚拟文件创建成功"
