name: Hardhat Test (禁用)

on:
  # 仅在手动触发且提供特定密钥时运行
  workflow_dispatch:
    inputs:
      run_key:
        description: "运行密钥"
        required: true

jobs:
  hardhat-test:
    # 添加条件使其永远不会运行
    if: github.event.inputs.run_key == 'special_run_key_20231231'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/hardhat

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: backend/hardhat/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Compile contracts
        run: yarn compile

      - name: Ensure deployed directory exists
        run: mkdir -p deployed

      - name: Run tests
        run: yarn test
