name: 回滚部署 (禁用)

# 仅在手动触发且提供特定密钥时运行
on:
  workflow_dispatch:
    inputs:
      run_key:
        description: "运行密钥"
        required: true
      commit_sha:
        description: "回滚到的提交SHA"
        required: true
      environment:
        description: "部署环境"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs:
  rollback:
    # 添加条件使其永远不会运行
    if: github.event.inputs.run_key == 'special_run_key_20231231'
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      - name: 部署回滚版本
        run: |
          echo "回滚到 ${{ github.event.inputs.commit_sha }} 在 ${{ github.event.inputs.environment }} 环境"
          # 这里添加实际部署回滚版本的命令
