name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_ENV: test
  COVERAGE_THRESHOLD_STATEMENTS: 50
  COVERAGE_THRESHOLD_BRANCHES: 30
  COVERAGE_THRESHOLD_FUNCTIONS: 45
  COVERAGE_THRESHOLD_LINES: 50

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: backend/yarn.lock

      - name: Install backend dependencies
        working-directory: ./backend
        run: yarn install --frozen-lockfile

      - name: Run tests with coverage
        working-directory: ./backend
        run: yarn test:ci

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            backend/coverage/coverage-summary.json
            backend/coverage/lcov-report/
          retention-days: 7

      - name: Check coverage thresholds
        working-directory: ./backend
        run: |
          if [ ! -f coverage/coverage-summary.json ]; then
            echo "Coverage file not found"
            exit 1
          fi

          COVERAGE=$(cat coverage/coverage-summary.json)
          STATEMENTS=$(echo $COVERAGE | jq -r '.total.statements.pct')
          BRANCHES=$(echo $COVERAGE | jq -r '.total.branches.pct')
          FUNCTIONS=$(echo $COVERAGE | jq -r '.total.functions.pct')
          LINES=$(echo $COVERAGE | jq -r '.total.lines.pct')

          if (( $(echo "$STATEMENTS < $COVERAGE_THRESHOLD_STATEMENTS" | bc -l) )); then
            echo "Statements coverage ($STATEMENTS%) is below threshold ($COVERAGE_THRESHOLD_STATEMENTS%)"
            exit 1
          fi

          if (( $(echo "$BRANCHES < $COVERAGE_THRESHOLD_BRANCHES" | bc -l) )); then
            echo "Branches coverage ($BRANCHES%) is below threshold ($COVERAGE_THRESHOLD_BRANCHES%)"
            exit 1
          fi

          if (( $(echo "$FUNCTIONS < $COVERAGE_THRESHOLD_FUNCTIONS" | bc -l) )); then
            echo "Functions coverage ($FUNCTIONS%) is below threshold ($COVERAGE_THRESHOLD_FUNCTIONS%)"
            exit 1
          fi

          if (( $(echo "$LINES < $COVERAGE_THRESHOLD_LINES" | bc -l) )); then
            echo "Lines coverage ($LINES%) is below threshold ($COVERAGE_THRESHOLD_LINES%)"
            exit 1
          fi
